# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DouYu' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    pod 'Alamofire', '4.7.2'
    pod 'SwiftyJSON', '3.1.3'                 # json 解析
    pod 'HandyJSON', '4.1.1'
    # pod 'SnapKit'                # UI布局组件
    pod 'Kingfisher', '4.7.0'                 # 图片下载缓存转码等
    pod 'IBAnimatable'
     pod 'SnapKit'
    
    
    # Pods for DouYu
    
    target 'DouYuTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'DouYuUITests' do
        inherit! :search_paths
        # Pods for testing
    end

end
